# Generated by Django 3.2 on 2021-05-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('country', 'city', 'name')},
        ),
    ]
